### ISSUE TITLE
Error with dynclipy 

### ISSUE THREAD

**Issue by Bio-data-tricks** [dynverse/dynclipy#1]
Hi, 
I try to use dynclipy but I get an error :

AttributeError                            Traceback (most recent call last)
Cell In [1], line 1
----> 1 import dynclipy
      2 import pandas as pd

File ~\Anaconda3\envs\renv\lib\site-packages\dynclipy-0.1-py3.9.egg\dynclipy\__init__.py:9
      6 from rpy2.robjects import numpy2ri
      7 numpy2ri.activate()
----> 9 from .read import check_conversion_rpy2py, main
     10 from .write import write_output
     11 from .dataset import *

File ~\Anaconda3\envs\renv\lib\site-packages\dynclipy-0.1-py3.9.egg\dynclipy\read.py:13
     10 import pandas as pd
     11 import random
---> 13 @ro.conversion.rpy2py.register(rinterface.SexpS4)
     14 def convert_sparse(obj):
     15     if "dgCMatrix" in obj.rclass:
     16         x = obj.do_slot("x")

AttributeError: 'function' object has no attribute 'register'

Have you an idea ? 
Thanks 

Nicolas

**Comment by Bio-data-tricks** [comment]
Hi, I still can't run the code. I installed dynclipy, made the updates, but I always get this error message.  The yml and py file are in the same folder.
Thanks 
Nicolas

C:\Users\cosmic\Desktop\DIFFERENTIATION>python run.py
R[write to console]: Error: --dataset should contain a pathname of a .loom or .h5 file. Add a '-h' flag for help.

Traceback (most recent call last):
  File "run.py", line 4, in <module>
    dataset = dynclipy.main()
  File "C:\Users\cosmic\AppData\Local\Programs\Python\Python37\lib\site-packages\dynclipy-0.1-py3.7.egg\dynclipy\read.py", line 123, in main
    """)
  File "C:\Users\cosmic\AppData\Local\Programs\Python\Python37\lib\site-packages\rpy2\robjects\__init__.py", line 438, in __call__
    res = self.eval(p)
  File "C:\Users\cosmic\AppData\Local\Programs\Python\Python37\lib\site-packages\rpy2\robjects\functions.py", line 199, in __call__
    .__call__(*args, **kwargs))
  File "C:\Users\cosmic\AppData\Local\Programs\Python\Python37\lib\site-packages\rpy2\robjects\functions.py", line 125, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
  File "C:\Users\cosmic\AppData\Local\Programs\Python\Python37\lib\site-packages\rpy2\rinterface_lib\conversion.py", line 45, in _
    cdata = function(*args, **kwargs)
  File "C:\Users\cosmic\AppData\Local\Programs\Python\Python37\lib\site-packages\rpy2\rinterface.py", line 680, in __call__
    raise embedded.RRuntimeError(_rinterface._geterrmessage())
rpy2.rinterface_lib.embedded.RRuntimeError: Error: --dataset should contain a pathname of a .loom or .h5 file. Add a '-h' flag for help.

**Comment by Bio-data-tricks** [comment]
Hi, 
I have a new error...

R[write to console]: Error in "optparse::parse_args_helper()" : 
  Error in getopt(spec = spec, opt = args) : short flag "f" is invalid
